# Generated by Django 5.0.4 on 2024-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
