# Generated by Django 5.0.4 on 2024-11-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0005_game_about_game_image_game_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='gameApp.category'),
        ),
    ]
