# Generated by Django 5.0.4 on 2024-11-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0007_alter_order_status_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
